default['teamcity']['version'] = '7.1.5'
default['teamcity']['install_dir'] = '/home/teamcity/'
default['teamcity']['data_path'] = '/home/teamcity/TeamCityData'
default['teamcity']['java_home'] = '/usr/lib/jvm/default-java'
default['teamcity']['user']['name'] = 'teamcity'
